name: Build Proxy EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller requests pyyaml pystray pillow pywin32

      - name: Build executables
        run: |
          pyinstaller cfnatddns.py --onefile --noconsole --name cfnatddns --icon=icon.ico
          pyinstaller cfupload.py  --onefile --noconsole --name cfupload
          pyinstaller ipfilter.py  --onefile --noconsole --name ipfilter

      - name: Zip all executables
        run: powershell Compress-Archive -Path dist\* -DestinationPath proxy_tools_bundle.zip

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: proxy_tools_bundle
          path: proxy_tools_bundle.zip
