name: Build Proxy EXE

on:
  workflow_dispatch:  # 只允许手动触发

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller pyyaml requests

      - name: Build executable
        run: |
          pyinstaller cfnatddns.py --onefile --name cfnatddns --hidden-import=yaml

      - name: Prepare bundle directory
        run: |
          mkdir dist_bundle
          copy dist\cfnatddns.exe dist_bundle\
          copy config.yaml dist_bundle\

      - name: Zip bundle
        run: powershell Compress-Archive -Path dist_bundle\* -DestinationPath cfnatddns.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cfnatddns_bundle
          path: cfnatddns.zip
