name: Build EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyinstaller requests

      - name: Build executable
        run: |
          pyinstaller cfnatddns.py --onefile --name cfnatddns

          mkdir dist_bundle
          copy dist\cfnatddns.exe dist_bundle\cfnatddns.exe
          copy config.json dist_bundle\

      - name: Zip output
        run: powershell Compress-Archive -Path dist_bundle\* -DestinationPath cfnatddns.zip

      - name: Upload EXE ZIP
        uses: actions/upload-artifact@v4
        with:
          name: cfnatddns_bundle
          path: cfnatddns.zip
