name: Build EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyinstaller PyQt5

      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole --icon=icon.ico main.py
          mkdir dist_bundle
          copy dist\\main.exe dist_bundle\\cf_updater.exe
          copy config.json dist_bundle\\
          copy port_config.json dist_bundle\\
          copy icon.ico dist_bundle\\

      - name: Zip output
        run: powershell Compress-Archive -Path dist_bundle\\* -DestinationPath cf_updater.zip

      - name: Upload EXE ZIP
        uses: actions/upload-artifact@v4
        with:
          name: cf_updater_bundle
          path: cf_updater.zip
